<div class='modal fade' id='deleteModal<?= $seller->id?>' tabindex='-1' aria-labelledby='deleteModalLabel' aria-hidden='true'>
    <div class='modal-dialog modal-dialog-centered'>
        <div class='modal-content'>
            <div class='modal-header bg-danger text-white'>
                <h5 class='modal-title' id='deleteModalLabel'><?= $user->user ?>,</h5>
                <button type='button' class='btn-close btn-close-white' data-bs-dismiss='modal'
                    aria-label='Close'></button>
            </div>
            <div class='modal-body'>
                <p class='mb-0'>Estas seguro que deseas borrar a <?= $seller->nombre ?>?</p>
                <p>Tambien se borraran todas sus ventas.
                </p>
            </div>
            <div class='modal-footer'>
                <button type='button' class='btn btn-secondary' data-bs-dismiss='modal'>Cancelar</button>
                <a href="<?php BASE_URL ?> eliminar/vendedor/<?=$seller->id ?>"" type='button' class='btn btn-danger'
                    id='confirmDelete'><i class="bi bi-trash-fill me-2"></i>Eliminar</a>
            </div>
        </div>
    </div>
</div>

