<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <base href="<?php echo BASE_URL ?>" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="css/styles.css">
  <title>Tienda Computacion</title>
</head>
<body>

<div class="error-page d-flex align-items-center justify-content-center">
    <div class="error-container text-center p-4">
        <h1 class="error-code mb-0">Oops!</h1>
        <h2 class="display-6 error-message mb-3">Algo salio mal...</h2>
        <p class="lead error-message mb-5">Parece que la pagina solicitada no existe.</p>
        <a href="home" class="btn btn-glass px-4 py-2">Home</a>
        <a href="javascript:history.back()" class="btn btn-glass px-4 py-2">Volver atrás</a>


    </div>
</div>
<?= require_once "templates/layout/footer.phtml" ?>