<?php require_once 'templates/layout/header.php'; ?>

<form action="login" method="POST" class="container mt-5" style="max-width: 400px;">
  <div class="card shadow-sm p-4">
    <h3 class="text-center mb-4">Iniciar sesión</h3>

    <div class="mb-3">
      <label for="user" class="form-label">Usuario</label>
      <input type="text" class="form-control" id="user" name="user" placeholder="Ingresa tu usuario" required>
    </div>

    <div class="mb-3">
      <label for="password" class="form-label">Contraseña</label>
      <input type="password" class="form-control" id="password" name="password" placeholder="Ingresa tu contraseña" required>
    </div>

    <button type="submit" class="btn btn-primary w-100">Login</button>
  </div>
</form>




<?php require_once 'templates/layout/footer.php';?>