<section class="w-100 px-4 py-5" style="background-color: #9de2ff; border-radius: .5rem .5rem 0 0;">
    <div class="row d-flex justify-content-center">
        <div class="col col-md-9 col-lg-7 col-xl-5">
            <div class="card justify-content-center" style="border-radius: 15px">
                <div class="card-body p-5">
                    <div class="d-flex">

                        <div class="flex-shrink-0">
                            <!-- Foto de perfil vendedor -->
                            <img src="http:<?= BASE_URL . $seller->imagen ?>" alt="imagen vendedor"
                                class="img-fluid mb-1" style="width: 180px; border-radius: 10px;">

                            <form action="<?= BASE_URL ?>updateSeller/<?= htmlspecialchars($seller->id) ?>"
                                method="post" class="d-flex col justify-content-end" enctype="multipart/form-data">
                                <?php if ($user): ?>
                                    <div class="btn-group">
                                        <a href="editarVendedor/<?= $seller->id ?>" class="btn btn-warning">Editar</a>
                                        <label for="imagen" class="btn btn-success">Cambiar foto</label>
                                    </div>
                                <?php endif; ?>
                                <input type="file" class="btn" id="imagen" name="imagen" accept="image/*"
                                    onchange="this.form.submit();" hidden>
                            </form>

                        </div>


                        <div class="d-flex row flex-grow-1 ms-5 align-items-center">
                            <h5 class="mb-1"><?= $seller->nombre ?></h5>
                            <p class="mb-2 pb-1"><?= $seller->email ?></p>
                            <div class="d-flex justify-content-start rounded-3 p-2 mb-2 bg-body-tertiary">
                                <div>
                                    <p class="small text-muted mb-1">Total ventas:</p>
                                    <p class="mb-0"><?= $totalVentas ?></p>
                                </div>
                                <div class="px-3">
                                    <p class="small text-muted mb-1">Telefono</p>
                                    <p class="mb-0"><?= $seller->telefono ?></p>
                                </div>
                                <div class="px-3">
                                    <p class="small text-muted mb-1">ID</p>
                                    <p class="mb-0"><?= $seller->id ?></p>
                                </div>

                            </div>
                            <div class="d-flex justify-content-end">
                                <a href="<?= BASE_URL ?>vendedores" class="btn btn-outline-primary align-self-end">Ver
                                    más vendedores</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
</section>